name: CI

permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: "pnpm"
          cache-dependency-path: pnpm-lock.yaml

      - name: Enable corepack
        run: corepack enable

      - name: Verify versions
        run: |
          node -v
          pnpm -v

      - name: Install OS build tools (for native parser)
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate grammar sources
        run: pnpm ts:gen

      - name: Build native parser
        run: pnpm ts:build-native

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 4.0.15

      - name: Build WASM parser
        run: pnpm ts:build-wasm

      - name: Smoke test grammar (parse + highlight sample)
        run: |
          pnpm ts:parse:sample
          pnpm ts:highlight:sample

      - name: Build
        run: pnpm build

      - name: Lint
        run: pnpm lint

      - name: Typecheck
        run: pnpm typecheck

      - name: Test
        run: pnpm test
