name: Rust Checks
permissions:
  contents: read

on:
  pull_request:
  push:
    branches: [main]

jobs:
  rust:
    name: Format, Clippy, Tests (story-core)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust (stable) with components
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Cache cargo registry + build
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: rust-${{ runner.os }} # stable key across jobs

      - name: cargo fmt --all -- --check
        run: cargo fmt --all -- --check

      - name: cargo clippy (story-core)
        run: cargo clippy -p story-core -- -D warnings

      - name: cargo test (story-core)
        run: cargo test -p story-core --all-features

      - name: cargo doc (story-core)
        run: RUSTDOCFLAGS="-D warnings" cargo doc -p story-core --no-deps

  # Note: src-tauri clippy/build to be wired later as platform setup stabilizes.
